---
title: "Homework 1"
author:
- Paula Natascha Gillessen ()
- Julian Sandalek ()
- Julian Hofmaninger (12413122, h12413122@s.wu.ac.at)
date: "2025-10-25"
output:
  pdf_document: default
  html_document: default
subtitle: "Course 0214 - Statistics for Economics with R"
---



# 1. Basic R Operations
## Task 1
```{r basic r operations 1}
numseq <- rep(seq(1,7,by=3), each=4) * c(-1,1)
complexseq <- c(rep(c(4,2,0), 2), rep(c(7,14,21), 3))
charpattern <- LETTERS[seq(2,26, by=2)]
numseq;complexseq;charpattern
```

## Task 2
```{r basic r operations 2.1}
vec <- 0:12
vec
```

```{r basic r operations 2.2}
vec[vec %% 2 == 1] <- NA
na_idx <- which(is.na(vec))
vec[na_idx] <- vec[na_idx-1]+vec[na_idx+1]
na_idx;vec
```
\newpage
## Task 3
```{r basic r operations 3}
set.seed(1)
randvec <- rnorm(50, 0, 1)
subsetvec <- randvec[randvec > .5]
sum <- sum(randvec > 1)
randvec;subsetvec;sum
```

## Task 4
```{r basic r operations 4}
mat <- matrix(1:25, nrow=5, byrow=TRUE)
mat[4,];mat[,ncol(mat)];dim(mat)
```

# 2. Analysis of Data on US States
## Task 1
```{r analysis of data on us states 1}
state <- as.data.frame(state.x77)
names(state) <- make.names(names(state))
variable_names <- names(state) 
variable_names
```

Using the command `str(state)` we can explore the structure of the dataset. The output of this command also tells us the datatypes of the variables. After inspecting the output we can see that all variables are numerical, hence none is a categorical variable.

## Task 2
```{r analysis of data on us states 2}
LowEdu <- ifelse(state$HS.Grad < 48, TRUE, FALSE)
HighEdu <- ifelse(state$HS.Grad > 60, TRUE, FALSE)
MixedEdu <- ifelse(state$HS.Grad >= 48 & state$HS.Grad <= 60, TRUE, FALSE)
```

## Task 3
```{r analysis of data on us states 3}
LowEduNum <- ifelse(LowEdu, 1, 0)
EduStatus <- MixedEdu + 2 * HighEdu
table(EduStatus)
```

## Task 4
```{r analysis of data on us states 4.1}
EduStatus <- as.factor(EduStatus)
```

```{r analysis of data on us states 4.2}
levels(EduStatus) <- c("Low Education", "Mixed", "High Education")
state <- transform(state, Education_category=EduStatus)
head(state[1:2, c(1,ncol(state))])
```

## Task 5
```{r analysis of data on us states 5}
state <- transform(state, Education_category=EduStatus)
head(state[1:2, c(1,ncol(state))])
```

## Task 6
```{r analysis of data on us states 6}
low_education_data <- state[state$Education_category 
                            == "Low Education", c("Illiteracy", "Life.Exp")]
head(low_education_data,2)
```



